name: "Publish Tritón"
on:
  release:
    types:
      - created
jobs:
  test-publish:
    runs-on: windows-latest
    env:
      Solution_Name: src/Triton.sln
      Configuration: Release
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Install Codecov
      run: choco install codecov -y
    - name: Build and test Tritón
      run: dotnet test $env:Solution_Name --configuration=$env:Configuration --collect:"XPlat Code Coverage" --results-directory .\Build\tests --DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
    - name: Upload code coverage report
      run: foreach ($j in (ls .\Build\tests\ -Directory)) { codecov -f "$($j.FullName)\coverage.opencover.xml" }
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    - name: Get tag name
      uses: olegtarasov/get-tag@v2.1
    - name: Create NuGet Packages
      run: dotnet pack $env:Solution_Name --configuration=$env:Configuration -p:Version=$env:GIT_TAG_NAME -p:RepositoryBranch=${{ github.ref }} -p:RepositoryCommit=${{ github.sha }} -p:ContinuousIntegrationBuild=true
    - name: Push packages to GitHub
      run: dotnet nuget push "Build/**/*.nupkg" -k $env:GhToken --skip-duplicate --source "https://nuget.pkg.github.com/TheXDS/"
      env:
        GhToken: ${{ secrets.GITHUB_TOKEN }}
    - name: Push packages to NuGet
      run: dotnet nuget push "Build/**/*.nupkg" -k $env:NgToken --skip-duplicate --source "https://api.nuget.org/v3/index.json"
      env:
        NgToken: ${{ secrets.NUGET_TOKEN }}
